language: node_js
node_js:
  - 8.10.0

jobs:
  include:
    - stage: test
      install:
        - npm install -g codecov
      before_script:
        - npm install
      branches:
        only:
          - master
      cache:
        yarn: true
      script:
        - npm run test
    - stage: docs
      branches:
        only:
          - master
      cache:
        yarn: true
      script:
        - git config --global user.name "${GH_NAME}"
        - git config --global user.email "${GH_EMAIL}"
        - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        - cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages
      if: (type != pull_request)